// samples/angular-chat/src/app/user/login/login.component.ts
import {Component, OnInit} from '@angular/core';
import {Router} from '@angular/router';
import {LoginModel} from './loginModel';
import {UserService} from '../user.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  public loginModel = new LoginModel();
  public userNameRegExString = '^[a-zA-Z]{1}[\\w]{2,19}$';
  public userLoginRegExString = '^[a-zA-Z]{1}[\\w]{2,19}$';
  userNameFocused = true;
  userLoginFocused = true;
  private successUnSubscribe$;

  constructor(private userService: UserService, private router: Router) {
  }

  ngOnInit() {
    this.successUnSubscribe$ = this.userService.successSubject.subscribe(success => {
      if (success) {
        this.router.navigate(['dashboard']);
      }
    });
  }

  public onSubmit() {
    if (this.userNameFocused && this.userLoginFocused) {
      console.log('Login form passed validation and ready to submit.');
      this.userService.login(this.loginModel);
    } else {
      console.log('Login form failed validation');
    }
  }

  onChange() {
    this.userNameFocused = new RegExp(this.userNameRegExString).test(this.loginModel.userName);
    this.userLoginFocused = new RegExp(this.userLoginRegExString).test(this.loginModel.userLogin);
  }
}

<div class="login__wrapper">
  <div class="login__container">
    <div class="login__inner">
      <div class="login__top">
        <a class="login__logo" href="https://quickblox.com/">
          <img alt="QuickBlox" src="../../../assets/img/qb-logo.svg">
        </a>
        <h1>Quickblox Chat Sample</h1>
        <h3>Please enter Username and login</h3>
      </div>
      <form #loginForm="ngForm" (ngSubmit)="onSubmit()" class="login__form" name="loginForm">
        <div [class.error]="!userLoginFocused" [class.filled]="loginModel.userLogin" class="login_form__row">
          <label for="userLogin">Login</label>
          <input [(ngModel)]="loginModel.userLogin" (ngModelChange)="onChange()" id="userLogin" name="userLogin"
                 pattern="{{ userLoginRegExString }}"
                 required
                 title="Field should contain alphanumeric characters only in a range 3 to 20. The first character must be a letter."
                 type="text">
        </div>
        <div [class.error]="!userNameFocused" [class.filled]="loginModel.userName" class="login_form__row">
          <label for="userName">Username</label>
          <input [(ngModel)]="loginModel.userName" (ngModelChange)="onChange()" id="userName" name="userName"
                 pattern="{{ userNameRegExString }}"
                 required
                 title="Field should contain alphanumeric characters only in a range 3 to 20. The first character must be a letter."
                 type="text">
        </div>
        <div class="login__button_wrap">
          <button [disabled]="!loginForm.valid" class="btn m-login__button j-login__button" name="login_submit"
                  type="submit"> LOGIN
          </button>
        </div>
      </form>
    </div>
    <div class="login__footer">
      <div class="footer__logo_wrap">
        <a class="footer__logo" href="https://quickblox.com/">
          <img alt="QuickBlox" src="../../../assets/img/qblogo-grey.svg">
        </a>
        <p>by QuickBlox</p>
      </div>
      <span class="footer__version">v. 2.12.1:1084</span>
    </div>
  </div>
</div>

// samples/react-chat/src/Login/Login.tsx
import React, {useEffect, useState} from 'react';
import './Login.scss';
import qbLogoGray from '../assets/img/qblogo-grey.svg';
import { MainButton, TypeButton } from 'quickblox-react-ui-kit';

export type UserData = {
    userName: string;
    password: string;
    fullName?: string;
};

export type FunctionTypeLoginDataToVoid = (data: UserData) => void;

type LoginProps = {
    loginHandler?: FunctionTypeLoginDataToVoid;
};

const Login: React.FC<LoginProps> = ({ loginHandler }: LoginProps) => {
    const messageValidatorUserName = "The field should contain alphanumeric characters only in a range 3 to 20. The first character must be a letter.";
    const messageValidatorUserPassword = "The field cannot be empty.";

    const [userName, setUserName] = useState('');
    const [userPassword, setUserPassword] = useState('');
    const [validInputValue, setValidInputValue] = useState(false);
    const [stateTheme, setStateTheme] = useState({ theme: 'light'});


    useEffect( ()=> {
        if (
            (userName.length >= 3 && userName.length <= 20)
            && (userPassword.length >= 9)
        ) {
            setValidInputValue(true);
        }
        else {
            setValidInputValue(false);
        }

    }, [userName, userPassword]);

    const submitForm = () => {
        const data = {
            userName: userName,
            password: userPassword,
            nameTheme: stateTheme.theme
        };

        console.log('data: ', data);

        if (loginHandler) {
            loginHandler(data);
        }
    };

    const onChangeThemeHandler = (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        event.persist();
        const { id, value } = event.target;
        setStateTheme(prev => ({...prev, theme: id}))
    };

    return(
        <div className="login__wrapper">
            <div className="login__container">
                <div className="login__inner">
                    <div className="login__top">
                        <a className="login__logo" href="https://quickblox.com/">
                            <img alt="QuickBlox" src="https://quickblox.com/wp-content/themes/QuickbloxTheme2021/img/header-logo.svg" />
                        </a>

                        <h1>QB UIKit React Sample</h1>

                        <h3>Please enter Username and password</h3>
                    </div>
                    <form className="login__form" >
                        <div className="login_form__row">
                            <input
                                value = {userName}
                                onChange={(e) => setUserName(e.target.value) }
                                required
                                title={messageValidatorUserName}
                                type="text"
                                placeholder="User name"
                            />
                        </div>
                        <div className="login_form__row">
                            <input
                                value = {userPassword}
                                onChange={(e) => setUserPassword(e.target.value) }
                                required
                                title={messageValidatorUserPassword}
                                type="password"
                                placeholder="Password"
                            />
                        </div>
                        <div className='login_form__row-rbtn'>
                            <input
                                value="light"
                                type="radio"
                                id="light"
                                name="theme"
                                checked={stateTheme.theme === 'light'}
                                onChange={onChangeThemeHandler}
                            />
                            <label htmlFor="lightTheme">Light Theme</label> <br/>

                            <input
                              value="dark"
                              type="radio"
                              id="dark"
                              name="theme"
                              checked={stateTheme.theme === 'dark'}
                              onChange={onChangeThemeHandler}
                            />
                            <label htmlFor="darkTheme" style={{color: '#202F3E'}}>Dark Theme</label> <br/>
                            <br />
                        </div>
                        <div className="login__button_wrap">
                            <MainButton
                                title="Login"
                                typeButton={TypeButton.outlined}
                                disabled={!validInputValue}
                                clickHandler = {submitForm}
                                styleBox={{width: "304px"}}
                            />
                        </div>
                    </form>
                </div>
                <div className="login__footer">
                    <div className="footer__logo_wrap">
                        <a className="footer__logo" href="https://quickblox.com/">
                            <img alt="QuickBlox" src={qbLogoGray} />
                        </a>
                        <p>by QuickBlox</p>
                    </div>
                    <span className="footer__version">v. 0.1.0</span>
                </div>
            </div>
        </div>
        )}

export default Login;
